### ISSUE TITLE
Template is not used if user selects tag after entering text

### ISSUE THREAD

**Issue by tipa** [askvortsov1/flarum-discussion-templates#10]
It appears that when the user creates a new discussion post without a tag (with the "Start discussion" button on the Flarum main page), then writes something and selects a tag afterwards, the template is not being filled into the text box.
Perhaps this logic is used to prevent loss of data / the already written text.
I would prefer a logic that prepends the template to the already existing text.
I want the user to see/acknowledge/use the predefined template even if he first writes his post and then selects a tag afterwards.

**Comment by askvortsov1** [comment]
> Perhaps this logic is used to prevent loss of data / the already written text.

That's exactly right. I'm not sure about appending it at the bottom without asking the user; if someone is switching between tags, that might be annoying.

What if we used a JS prompt to ask whether they'd like the new template to be appended at the bottom?

**Comment by tipa** [comment]
My gut feeling is that a prompt would confuse the user, because they might not know about the template and decline it for that (or another) reason.
I am using my forum to provide support and allow submitting feature requests for my apps and for me it is desired that users read some "posting guidelines" (e.g. check for app updates, check if feature request has been submitted before, make sure to include OS version) before they are posting a new discussion - similar to many GitHub issue templates. Previously I used sticky "Read this before posting" posts in each subforum, however it didn't work as users seem to not read them.

Therefore I would prefer if the template is inserted without user confirmation at a place (either at the start or end of the post) where the user would certainly see it before hitting the "post" button.

**Comment by askvortsov1** [comment]
I see. I think that's reasonable; I'll add a setting in a setting in admin to toggle this behavior

**Comment by askvortsov1** [comment]
Done in v0.5.0

**Comment by tipa** [comment]
Unfortunately, this is not working entirely in 0.6.0.
To reproduce:
- User clicks "Start a Discussion" on main page
- writes some text
- clicks "Post discussion"
- popup shows to select tag -> user selects tag
- template is appended in the editor and visible for a short time but it does not appear in the submitted post

To fix this, the discussion should not be posted immediately after selecting a tag, so the user can read the inserted template and has to click the "Post discussion" button again.
If this is not possible to fix because of how Flarum works, would it perhaps be possible to define a template for entries without a tag? I am using your extension for a few days now and nearly anybody seems to have read the template. Everyone seems to start a discussion from the main page and select tags after writing their text. So having a generic template for new posts without tag would be desirable.
