### ISSUE TITLE
Comments should be ignored

### ISSUE THREAD

**Issue by JCKodel** [askvortsov1/flarum-discussion-templates#2]
Let's assume my template is this:

```
<!--
Attention users: this is an important rule!
Read all of this.
-->

### Title

[Put your title here]
```

When editing the `[Put your title here]` and hit post, all contents inside `<--` and `-->` should be automatically deleted.

**Comment by askvortsov1** [comment]
All this extension does is populate the composer with templates. I agree that it'd be nice for comments to not show up, but that's more of a markdown / bbcode issue than one here
