### ISSUE TITLE
Changed template when tag is changed

### ISSUE THREAD

**Issue by tipa** [askvortsov1/flarum-discussion-templates#9]
When creating a new discussion, the correct template is being filled into the editor after the first tag has been chosen.
But when this tag is removed and another tag is being selected, the template is not changed to the template of the other tag. I think it would be great if that would be the case

**Comment by askvortsov1** [comment]
Hi, thanks for the report! Is this a separate issue from https://github.com/askvortsov1/flarum-discussion-templates/issues/10? IE, are you experiencing this even when there has been no text entered by the user before changing tags?

**Comment by tipa** [comment]
Yes this is a separate issue. The text is not changing correctly to the new tag's template even when the user has not typed any text.
I made it two separate issues because you might decide to implement one the two but not the other one (of course, both would be ideal for me 🙂)

**Comment by askvortsov1** [comment]
Hmm this feels like a bug then, probably slipped past me in a previous update. I'll get this fixed.

**Comment by askvortsov1** [comment]
Done in v0.5.0
